import type { ProfileView } from "@/types";

/** Illustrated, consent-safe placeholder avatars (no real people). */
function avatar(seed: string, variant = 0): string {
  const params = new URLSearchParams({
    seed: `${seed}-${variant}`,
    backgroundType: "gradientLinear",
    backgroundColor: "f7f0df,d8a33d,c7653a,354f3b",
  });
  return `https://api.dicebear.com/9.x/personas/svg?${params.toString()}`;
}

export const LIFESTYLE_INTERESTS = [
  "Fishing",
  "Hunting",
  "Camping",
  "Horses",
  "Farming",
  "Ranching",
  "Country Music",
  "Rodeos",
  "Trucks",
  "Bonfires",
  "Hiking",
  "Dogs",
  "Gardening",
  "Off-roading",
  "BBQ",
  "Line Dancing",
  "Small-town Life",
  "Homesteading",
] as const;

export const LANDING_CATEGORIES = [
  "Fishing",
  "Hunting",
  "Camping",
  "Horses",
  "Farming",
  "Country Music",
  "Rodeos",
  "Trucks",
  "Bonfires",
  "Hiking",
  "Dogs",
  "Gardening",
] as const;

export const PROMPT_QUESTIONS = [
  "My perfect Saturday looks like…",
  "The quickest way to my heart is…",
  "My ideal first date is…",
  "You should know that I…",
  "My most controversial country opinion is…",
  "I'll bring the beer if you…",
  "My dream piece of land would have…",
  "A green flag I always notice is…",
  "My favorite thing about country life is…",
] as const;

export const DEMO_PROFILES: ProfileView[] = [
  {
    id: "1",
    firstName: "Waylon",
    age: 29,
    gender: "man",
    pronouns: "he/him",
    bio: "Raised on a cattle ranch outside Amarillo. I fix fences by day and fix up an old Bronco by night. Looking for someone who doesn't mind mud on the truck floor.",
    occupation: "Ranch Hand",
    heightCm: 185,
    city: "Amarillo",
    state: "TX",
    distanceMiles: 4,
    relationshipIntention: "long_term",
    verified: true,
    online: true,
    photos: [avatar("waylon", 0), avatar("waylon", 1), avatar("waylon", 2)],
    interests: ["Ranching", "Trucks", "Country Music", "BBQ"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[0], answer: "Mending fence at sunrise, then a cold drink on the tailgate at sunset." },
      { id: "p2", question: PROMPT_QUESTIONS[1], answer: "Homemade cornbread and someone who can hold a conversation with my grandma." },
      { id: "p3", question: PROMPT_QUESTIONS[8], answer: "Everybody actually waves at everybody, even strangers." },
    ],
    profileComplete: true,
  },
  {
    id: "2",
    firstName: "Della",
    age: 27,
    gender: "woman",
    pronouns: "she/her",
    bio: "Vet tech who moonlights as a barrel racer. I've got two dogs, a horse named Biscuit, and a garden that's mostly tomatoes and good intentions.",
    occupation: "Veterinary Technician",
    heightCm: 165,
    city: "Bozeman",
    state: "MT",
    distanceMiles: 9,
    relationshipIntention: "dating",
    verified: true,
    online: false,
    photos: [avatar("della", 0), avatar("della", 1), avatar("della", 2)],
    interests: ["Horses", "Rodeos", "Dogs", "Gardening"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[2], answer: "A hike to a swimming hole, then tacos from the truck by the feed store." },
      { id: "p2", question: PROMPT_QUESTIONS[3], answer: "I talk to my horse more than most people, and he gives better advice." },
      { id: "p3", question: PROMPT_QUESTIONS[7], answer: "Somebody who's kind to waitstaff and animals, in that order of noticing." },
    ],
    profileComplete: true,
  },
  {
    id: "3",
    firstName: "Jed",
    age: 34,
    gender: "man",
    pronouns: "he/him",
    bio: "Fourth-generation farmer. Corn, soybeans, and a dog named Combine. I like slow mornings, bonfires, and people who ask good questions.",
    occupation: "Farmer",
    heightCm: 180,
    city: "Cedar Rapids",
    state: "IA",
    distanceMiles: 12,
    relationshipIntention: "marriage",
    verified: false,
    online: false,
    photos: [avatar("jed", 0), avatar("jed", 1)],
    interests: ["Farming", "Bonfires", "Dogs", "Hunting"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[0], answer: "Coffee on the porch, chores, then whatever the weather lets me do." },
      { id: "p2", question: PROMPT_QUESTIONS[4], answer: "Flannel is a year-round fabric, not a season." },
      { id: "p3", question: PROMPT_QUESTIONS[6], answer: "A pond stocked with bass and enough land that the neighbors are a good walk away." },
    ],
    profileComplete: true,
  },
  {
    id: "4",
    firstName: "Sunny",
    age: 25,
    gender: "woman",
    pronouns: "she/her",
    bio: "Line dancing instructor and part-time florist. My golden retriever thinks he's a person. I'm looking for my two-step partner for life.",
    occupation: "Florist",
    heightCm: 160,
    city: "Nashville",
    state: "TN",
    distanceMiles: 6,
    relationshipIntention: "long_term",
    verified: true,
    online: true,
    photos: [avatar("sunny", 0), avatar("sunny", 1), avatar("sunny", 2)],
    interests: ["Line Dancing", "Country Music", "Gardening", "Dogs"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[1], answer: "A well-worn pair of boots and the confidence to ask me to dance." },
      { id: "p2", question: PROMPT_QUESTIONS[2], answer: "Live music on a patio somewhere with string lights." },
      { id: "p3", question: PROMPT_QUESTIONS[8], answer: "Everyone knows your name at the diner by week two." },
    ],
    profileComplete: true,
  },
  {
    id: "5",
    firstName: "Cole",
    age: 31,
    gender: "man",
    pronouns: "he/him",
    bio: "Off-road guide on weekends, electrician the rest of the week. I'll teach you to drive stick if you teach me to two-step.",
    occupation: "Electrician",
    heightCm: 178,
    city: "Boise",
    state: "ID",
    distanceMiles: 15,
    relationshipIntention: "dating",
    verified: true,
    online: false,
    photos: [avatar("cole", 0), avatar("cole", 1)],
    interests: ["Off-roading", "Trucks", "Camping", "Fishing"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[5], answer: "...bring the tackle box. Deal?" },
      { id: "p2", question: PROMPT_QUESTIONS[0], answer: "Trail at sunrise, river by noon, campfire by dark." },
      { id: "p3", question: PROMPT_QUESTIONS[7], answer: "Someone who tips well and remembers the server's name." },
    ],
    profileComplete: true,
  },
  {
    id: "6",
    firstName: "Marlene",
    age: 38,
    gender: "woman",
    pronouns: "she/her",
    bio: "Homesteader with chickens, goats, and a canning habit that's gotten out of hand. Widowed, healed up, and open to something real.",
    occupation: "Homesteader & Etsy Shop Owner",
    heightCm: 168,
    city: "Asheville",
    state: "NC",
    distanceMiles: 3,
    relationshipIntention: "long_term",
    verified: true,
    online: true,
    photos: [avatar("marlene", 0), avatar("marlene", 1), avatar("marlene", 2)],
    interests: ["Homesteading", "Gardening", "Small-town Life", "BBQ"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[3], answer: "I once named a rooster after my ex out of spite. He's a good rooster." },
      { id: "p2", question: PROMPT_QUESTIONS[8], answer: "Nobody's ever too busy to help you fix a flat." },
      { id: "p3", question: PROMPT_QUESTIONS[6], answer: "A big garden, a porch swing, and room for a few more goats." },
    ],
    profileComplete: true,
  },
  {
    id: "7",
    firstName: "Tanner",
    age: 23,
    gender: "man",
    pronouns: "he/him",
    bio: "Rodeo circuit rider, mostly bulls. Still figuring life out but I know I want somebody in my corner when the gate opens.",
    occupation: "Professional Rodeo Rider",
    heightCm: 175,
    city: "Cheyenne",
    state: "WY",
    distanceMiles: 20,
    relationshipIntention: "not_sure",
    verified: false,
    online: false,
    photos: [avatar("tanner", 0), avatar("tanner", 1)],
    interests: ["Rodeos", "Horses", "Trucks", "Country Music"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[4], answer: "Boots with jeans, no exceptions, fight me." },
      { id: "p2", question: PROMPT_QUESTIONS[2], answer: "Watching the sunset from the bed of my truck, tailgate down." },
      { id: "p3", question: PROMPT_QUESTIONS[7], answer: "Someone who roots for me even after a bad ride." },
    ],
    profileComplete: true,
  },
  {
    id: "8",
    firstName: "Ruth",
    age: 41,
    gender: "woman",
    pronouns: "she/her",
    bio: "School teacher by day, competitive pit-master on weekends. Divorced, no drama, love my students and my smoker in equal measure.",
    occupation: "Elementary School Teacher",
    heightCm: 163,
    city: "Tulsa",
    state: "OK",
    distanceMiles: 8,
    relationshipIntention: "marriage",
    verified: true,
    online: true,
    photos: [avatar("ruth", 0), avatar("ruth", 1), avatar("ruth", 2)],
    interests: ["BBQ", "Gardening", "Small-town Life", "Dogs"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[1], answer: "Brisket, done low and slow, and someone who appreciates the wait." },
      { id: "p2", question: PROMPT_QUESTIONS[0], answer: "Farmers market, smoker running by ten, friends over by five." },
      { id: "p3", question: PROMPT_QUESTIONS[8], answer: "Front porches are still where the real conversations happen." },
    ],
    profileComplete: true,
  },
  {
    id: "9",
    firstName: "Briar",
    age: 26,
    gender: "nonbinary",
    pronouns: "they/them",
    bio: "Forest service trail crew in summer, ski patrol in winter. Happiest with dirt under my nails and a dog at my heels.",
    occupation: "Trail Crew Lead",
    heightCm: 170,
    city: "Missoula",
    state: "MT",
    distanceMiles: 11,
    relationshipIntention: "dating",
    verified: true,
    online: false,
    photos: [avatar("briar", 0), avatar("briar", 1)],
    interests: ["Hiking", "Camping", "Dogs", "Fishing"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[2], answer: "A trailhead, a thermos of coffee, and no cell service." },
      { id: "p2", question: PROMPT_QUESTIONS[6], answer: "A creek, a treeline, and enough quiet to hear it." },
      { id: "p3", question: PROMPT_QUESTIONS[7], answer: "Somebody who packs out their own trash, literally and otherwise." },
    ],
    profileComplete: true,
  },
  {
    id: "10",
    firstName: "Hank",
    age: 45,
    gender: "man",
    pronouns: "he/him",
    bio: "Own a small feed store, coach my kid's little league team, and still change my own oil. Looking for a partner, not a project.",
    occupation: "Small Business Owner",
    heightCm: 182,
    city: "Lubbock",
    state: "TX",
    distanceMiles: 5,
    relationshipIntention: "long_term",
    verified: true,
    online: false,
    photos: [avatar("hank", 0), avatar("hank", 1)],
    interests: ["Trucks", "Hunting", "Small-town Life", "BBQ"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[3], answer: "I've coached little league for six years and I still cry at the trophy ceremony." },
      { id: "p2", question: PROMPT_QUESTIONS[0], answer: "Store opens at eight, ballgame by six, grill going after." },
      { id: "p3", question: PROMPT_QUESTIONS[8], answer: "You can still get a handshake deal done here." },
    ],
    profileComplete: true,
  },
  {
    id: "11",
    firstName: "Ivy",
    age: 30,
    gender: "woman",
    pronouns: "she/her",
    bio: "Large-animal vet who's seen it all at 3am in a barn. Off the clock I'm usually canning peaches or losing to my sister at cards.",
    occupation: "Veterinarian",
    heightCm: 167,
    city: "Lexington",
    state: "KY",
    distanceMiles: 7,
    relationshipIntention: "marriage",
    verified: true,
    online: true,
    photos: [avatar("ivy", 0), avatar("ivy", 1), avatar("ivy", 2)],
    interests: ["Horses", "Farming", "Gardening", "Country Music"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[1], answer: "Show up when things are hard, not just when they're easy." },
      { id: "p2", question: PROMPT_QUESTIONS[4], answer: "Sweet tea should never be unsweetened. It's not tea at that point." },
      { id: "p3", question: PROMPT_QUESTIONS[6], answer: "A barn, a pasture, and a porch big enough for the whole family." },
    ],
    profileComplete: true,
  },
  {
    id: "12",
    firstName: "Roy",
    age: 36,
    gender: "man",
    pronouns: "he/him",
    bio: "Fishing guide on the river most mornings, brew a mean batch of sweet tea, and I'm told I make a decent biscuit. Let's find out together.",
    occupation: "Fishing Guide",
    heightCm: 183,
    city: "Baton Rouge",
    state: "LA",
    distanceMiles: 10,
    relationshipIntention: "dating",
    verified: false,
    online: true,
    photos: [avatar("roy", 0), avatar("roy", 1)],
    interests: ["Fishing", "Camping", "Bonfires", "Dogs"],
    prompts: [
      { id: "p1", question: PROMPT_QUESTIONS[5], answer: "...don't mind the smell of the bait bucket." },
      { id: "p2", question: PROMPT_QUESTIONS[2], answer: "Sunrise on the water, then breakfast at the diner with the regulars." },
      { id: "p3", question: PROMPT_QUESTIONS[8], answer: "The pace of it. Nobody's in a hurry to nowhere." },
    ],
    profileComplete: true,
  },
];

export function getDemoProfileById(id: string): ProfileView | undefined {
  return DEMO_PROFILES.find((p) => p.id === id);
}

export const DEMO_TESTIMONIALS = [
  {
    name: "Callie & Beau",
    location: "near Waco, TX",
    quote:
      "We matched over a shared love of bad country puns and worse fishing luck. Eight months later he's teaching my kids to ride.",
    photo: avatar("callie-beau", 0),
  },
  {
    name: "Michael R.",
    location: "outside Bozeman, MT",
    quote:
      "Every other app felt like it was built for a city I don't live in. HillBilly Dating actually got what I was looking for.",
    photo: avatar("michael", 0),
  },
  {
    name: "Dawn P.",
    location: "near Asheville, NC",
    quote:
      "I wasn't sure a dating app could feel this unpretentious. Met my fiancé three months in, porch swing and all.",
    photo: avatar("dawn", 0),
  },
];
